[package]
name = "buraaq_borrow"
description = "Borrow checking and aliasing rules for Buraaq"
version.workspace = true
edition.workspace = true

[dependencies]
buraaq_diagnostics = { path = "../diagnostics" }
buraaq_ownership = { path = "../ownership" }
buraaq_source = { path = "../source" }
buraaq_types = { path = "../types" }
