use crate::TokenKind;

pub fn lookup(word: &str) -> TokenKind {
    match word {
        "async" => TokenKind::Async,
        "await" => TokenKind::Await,
        "break" => TokenKind::Break,
        "const" => TokenKind::Const,
        "continue" => TokenKind::Continue,
        "copy" => TokenKind::Copy,
        "defer" => TokenKind::Defer,
        "drop" => TokenKind::Drop,
        "else" => TokenKind::Else,
        "elif" => TokenKind::Elif,
        "enum" => TokenKind::Enum,
        "err" => TokenKind::Err,
        "extern" => TokenKind::Extern,
        "false" => TokenKind::False,
        "fn" => TokenKind::Fn,
        "for" => TokenKind::For,
        "give" => TokenKind::Give,
        "if" => TokenKind::If,
        "impl" => TokenKind::Impl,
        "in" => TokenKind::In,
        "match" => TokenKind::Match,
        "module" => TokenKind::Module,
        "mut" => TokenKind::Mut,
        "new" => TokenKind::New,
        "none" => TokenKind::None,
        "not" => TokenKind::Not,
        "ok" => TokenKind::Ok,
        "parallel" => TokenKind::Parallel,
        "pub" => TokenKind::Pub,
        "raise" => TokenKind::Raise,
        "ref" => TokenKind::Ref,
        "return" => TokenKind::Return,
        "self" => TokenKind::SelfKw,
        "some" => TokenKind::Some,
        "spawn" => TokenKind::Spawn,
        "struct" => TokenKind::Struct,
        "throws" => TokenKind::Throws,
        "trait" => TokenKind::Trait,
        "true" => TokenKind::True,
        "type" => TokenKind::Type,
        "unsafe" => TokenKind::Unsafe,
        "use" => TokenKind::Use,
        "void" => TokenKind::Void,
        "while" => TokenKind::While,
        "as" => TokenKind::As,
        "test" => TokenKind::Test,
        "bench" => TokenKind::Bench,
        "expect" => TokenKind::Expect,
        _ => TokenKind::Ident(word.to_owned()),
    }
}
